### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by rikako-yurino** [rikako-yurino/protospace-34770#1]
https://protospace-34770.herokuapp.com/

**Comment by kinnkann** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**◯プロトタイプが正しく投稿できた場合は、トップページへ遷移するようにしましょう**
現状、投稿した商品の「詳細ページ」へ遷移してしまいます。

修正が完了しましたら、再度以下の報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://docs.google.com/forms/d/e/1FAIpQLSdgFRc0G8WCpE3RuwCDon6yQU_zFA2lH-v04e1mfxdcQr4O0w/viewform

**Comment by rikako-yurino** [comment]
@kinnkann ご確認くださりありがとうございます。
下記修正いたしました。お手数ですが再度ご確認をお願いいたします。

「◯プロトタイプが正しく投稿できた場合は、トップページへ遷移」
https://protospace-34770.herokuapp.com/

**Comment by kinnkann** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
**◯ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
→現状、他のユーザーのプロトタイプ編集ページに遷移（して編集）できてしまいます。

**◯正しくプロトタイプを編集できた場合は、詳細ページへ遷移するようにしましょう**
→現状、トップページに遷移します。

あともう少しです！応援しています
修正が完了しましたら、再度以下の報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://docs.google.com/forms/d/e/1FAIpQLSdgFRc0G8WCpE3RuwCDon6yQU_zFA2lH-v04e1mfxdcQr4O0w/viewform

**Comment by rikako-yurino** [comment]
@kinnkann 
ご確認りがとうございます！

◯ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力
◯正しくプロトタイプを編集できた場合は、詳細ページへ遷移するようにしましょう

上記二箇所の修正が完了しました。
お手数ですが再度ご確認をお願いします。

https://protospace-34770.herokuapp.com/

**Comment by odada1117** [comment]
rikako-yurinoさん、ご提出ありがとうございます。
問題なく正常に動作することが確認できました！LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by rikako-yurino** [comment]
@odada1117 
ご確認ありがとうございました！
最終課題の案内の件も承知しました。
引き続きよろしくお願いします！
